# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jasnoorsandhu/XILINX_Projects/FFT/Reconfigurable_FFT/Reconfigurable_FFT.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
# IP: The module: 'design_1_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jasnoorsandhu/XILINX_Projects/FFT/Reconfigurable_FFT/Reconfigurable_FFT.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/jasnoorsandhu/XILINX_Projects/FFT/Reconfigurable_FFT/Reconfigurable_FFT.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1.xci
# IP: The module: 'design_1_auto_pc_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jasnoorsandhu/XILINX_Projects/FFT/Reconfigurable_FFT/Reconfigurable_FFT.srcs/sources_1/bd/design_1/ip/design_1_auto_pc_1/design_1_auto_pc_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_auto_pc_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
